SELECT * FROM Regiones;

INSERT INTO Regiones VALUES(1, 'Acámbaro');
INSERT INTO Regiones VALUES(2, 'Acapulco');
INSERT INTO Regiones VALUES(3, 'Acayucan');
INSERT INTO Regiones VALUES(4, 'Aguascalientes');
INSERT INTO Regiones VALUES(5, 'Autlán de Navarro');
INSERT INTO Regiones VALUES(6, 'Caborca');
INSERT INTO Regiones VALUES(6, 'Cadereyta');
INSERT INTO Regiones VALUES(6, 'Camargo');
INSERT INTO Regiones VALUES(6, 'Campeche');
INSERT INTO Regiones VALUES(6, 'Cancún');
INSERT INTO Regiones VALUES(6, 'Cd. Acuña');
INSERT INTO Regiones VALUES(6, 'Cd. Cuauhtémoc');
INSERT INTO Regiones VALUES(6, 'Cd. del Carmen');
INSERT INTO Regiones VALUES(6, 'Cd. Guzmán');
INSERT INTO Regiones VALUES(6, 'Cd. Juárez');
INSERT INTO Regiones VALUES(6, 'Cd. Nezahualcóyotl ');
INSERT INTO Regiones VALUES(6, 'Cd. Obregón');
INSERT INTO Regiones VALUES(6, 'Cd. Victoria');
INSERT INTO Regiones VALUES(6, 'CDMX Centro');
INSERT INTO Regiones VALUES(6, 'CDMX Norte');
INSERT INTO Regiones VALUES(6, 'CDMX Oriente');
INSERT INTO Regiones VALUES(6, 'CDMX Poniente');
INSERT INTO Regiones VALUES(6, 'CDMX Sur');
INSERT INTO Regiones VALUES(6, 'Celaya');
INSERT INTO Regiones VALUES(6, 'Chalco - Ixtapaluca');
INSERT INTO Regiones VALUES(6, 'Chetumal');
INSERT INTO Regiones VALUES(6, 'Chihuahua');
INSERT INTO Regiones VALUES(6, 'Chilpancingo');
INSERT INTO Regiones VALUES(6, 'Chimalhuacán');
INSERT INTO Regiones VALUES(6, 'Coacalco');
INSERT INTO Regiones VALUES(6, 'Coatzacoalcos');
INSERT INTO Regiones VALUES(6, 'Colima');
INSERT INTO Regiones VALUES(6, 'Comalcalco');
INSERT INTO Regiones VALUES(6, 'Comitán');
INSERT INTO Regiones VALUES(6, 'Córdoba');
INSERT INTO Regiones VALUES(6, 'Cozumel');
INSERT INTO Regiones VALUES(6, 'Cuautla');
INSERT INTO Regiones VALUES(6, 'Cuernavaca');
INSERT INTO Regiones VALUES(6, 'Culiacán');
INSERT INTO Regiones VALUES(6, 'Cunduacán');
INSERT INTO Regiones VALUES(6, 'Delicias');
INSERT INTO Regiones VALUES(6, 'Dolores Hidalgo');
INSERT INTO Regiones VALUES(6, 'Durango');
INSERT INTO Regiones VALUES(6, 'Ecatepec');
INSERT INTO Regiones VALUES(6, 'Emiliano Zapata');
INSERT INTO Regiones VALUES(6, 'Ensenada');
INSERT INTO Regiones VALUES(6, 'García');
INSERT INTO Regiones VALUES(6, 'Gómez Palacio');
INSERT INTO Regiones VALUES(6, 'Guadalajara');
INSERT INTO Regiones VALUES(6, 'Guasave');
INSERT INTO Regiones VALUES(6, 'Hermosillo');
INSERT INTO Regiones VALUES(6, 'Hidalgo del Parral');
INSERT INTO Regiones VALUES(6, 'Huatulco');
INSERT INTO Regiones VALUES(6, 'Huauchinango');
INSERT INTO Regiones VALUES(6, 'Iguala');
INSERT INTO Regiones VALUES(6, 'Irapuato');
INSERT INTO Regiones VALUES(6, 'Ixtlahuaca de Rayón');
INSERT INTO Regiones VALUES(6, 'Jiménez');
INSERT INTO Regiones VALUES(6, 'Jiutepec');
INSERT INTO Regiones VALUES(6, 'Jojutla');
INSERT INTO Regiones VALUES(6, 'La Paz');
INSERT INTO Regiones VALUES(6, 'La Piedad');
INSERT INTO Regiones VALUES(6, 'Lázaro Cárdenas');
INSERT INTO Regiones VALUES(6, 'León');
INSERT INTO Regiones VALUES(6, 'Linares');
INSERT INTO Regiones VALUES(6, 'Los Cabos');
INSERT INTO Regiones VALUES(6, 'Los Mochis');
INSERT INTO Regiones VALUES(6, 'Los Reyes La Paz');
INSERT INTO Regiones VALUES(6, 'Macuspana');
INSERT INTO Regiones VALUES(6, 'Macuspana');
INSERT INTO Regiones VALUES(6, 'Macuspana');
INSERT INTO Regiones VALUES(6, 'Macuspana');
INSERT INTO Regiones VALUES(6, 'Magdalena de Kino');
INSERT INTO Regiones VALUES(6, 'Manzanillo');
INSERT INTO Regiones VALUES(6, 'Martínez de la Torre');
INSERT INTO Regiones VALUES(6, 'Matamoros, Coahuila');
INSERT INTO Regiones VALUES(6, 'Matamoros, Tamaulipas');
INSERT INTO Regiones VALUES(6, 'Mazatlán');
INSERT INTO Regiones VALUES(6, 'Mérida');
INSERT INTO Regiones VALUES(6, 'Mexicali');
INSERT INTO Regiones VALUES(6, 'Minatitlán');
INSERT INTO Regiones VALUES(6, 'Monclova');
INSERT INTO Regiones VALUES(6, 'Montemorelos');
INSERT INTO Regiones VALUES(6, 'Monterrey (Cumbres)');
INSERT INTO Regiones VALUES(6, 'Monterrey Centro');
INSERT INTO Regiones VALUES(6, 'Monterrey Norte');
INSERT INTO Regiones VALUES(6, 'Monterrey Oriente');
INSERT INTO Regiones VALUES(6, 'Monterrey Sendero');
INSERT INTO Regiones VALUES(6, 'Monterrey Sur');
INSERT INTO Regiones VALUES(6, 'Morelia');
INSERT INTO Regiones VALUES(6, 'Muzquiz');
INSERT INTO Regiones VALUES(6, 'Nogales');
INSERT INTO Regiones VALUES(6, 'Nuevo  Laredo');
INSERT INTO Regiones VALUES(6, 'Nuevo Vallarta');
INSERT INTO Regiones VALUES(6, 'Oaxaca');
INSERT INTO Regiones VALUES(6, 'Ometepec');
INSERT INTO Regiones VALUES(6, 'Orizaba');
INSERT INTO Regiones VALUES(6, 'Pachuca');
INSERT INTO Regiones VALUES(6, 'Paraíso');
INSERT INTO Regiones VALUES(6, 'Parras de la Fuente');
INSERT INTO Regiones VALUES(6, 'Pátzcuaro');
INSERT INTO Regiones VALUES(6, 'Perinorte - Cuautitlán');
INSERT INTO Regiones VALUES(6, 'Playa del Carmen');
INSERT INTO Regiones VALUES(6, 'Puebla');
INSERT INTO Regiones VALUES(6, 'Puerto Peñasco');
INSERT INTO Regiones VALUES(6, 'Puerto Vallarta');
INSERT INTO Regiones VALUES(6, 'Querétaro');
INSERT INTO Regiones VALUES(6, 'Ramos Arizpe');
INSERT INTO Regiones VALUES(6, 'Reynosa');
INSERT INTO Regiones VALUES(6, 'Rosarito');
INSERT INTO Regiones VALUES(6, 'Sahuayo');
INSERT INTO Regiones VALUES(6, 'Salamanca');
INSERT INTO Regiones VALUES(6, 'Saltillo');
INSERT INTO Regiones VALUES(6, 'San Cristóbal de las Casas');
INSERT INTO Regiones VALUES(6, 'San Francisco del Rincón');
INSERT INTO Regiones VALUES(6, 'San Juan de los Lagos');
INSERT INTO Regiones VALUES(6, 'San Juan del Río');
INSERT INTO Regiones VALUES(6, 'San L Río Colorado');
INSERT INTO Regiones VALUES(6, 'San Luis Potosí');
INSERT INTO Regiones VALUES(6, 'San Pedro');
INSERT INTO Regiones VALUES(6, 'Santiago Tianguistenco de Galeana');
INSERT INTO Regiones VALUES(6, 'Sayula Jalisco');
INSERT INTO Regiones VALUES(6, 'Silao');
INSERT INTO Regiones VALUES(6, 'Tampico');
INSERT INTO Regiones VALUES(6, 'Tapachula');
INSERT INTO Regiones VALUES(6, 'Taxco');
INSERT INTO Regiones VALUES(6, 'Tecámac');
INSERT INTO Regiones VALUES(6, 'Tecate');
INSERT INTO Regiones VALUES(6, 'Tecomán');
INSERT INTO Regiones VALUES(6, 'Tehuacán');
INSERT INTO Regiones VALUES(6, 'Tepatitlán');
INSERT INTO Regiones VALUES(6, 'Tepeji del Río');
INSERT INTO Regiones VALUES(6, 'Tepic');
INSERT INTO Regiones VALUES(6, 'Teziutlán Puebla');
INSERT INTO Regiones VALUES(6, 'Tijuana');
INSERT INTO Regiones VALUES(6, 'Tizayuca');
INSERT INTO Regiones VALUES(6, 'Tlajomulco');
INSERT INTO Regiones VALUES(6, 'Tlaxcala');
INSERT INTO Regiones VALUES(6, 'Toluca');
INSERT INTO Regiones VALUES(6, 'Tonalá');
INSERT INTO Regiones VALUES(6, 'Torreón');
INSERT INTO Regiones VALUES(6, 'Tuxpan');
INSERT INTO Regiones VALUES(6, 'Tuxtepec');
INSERT INTO Regiones VALUES(6, 'Tuxtla Gutiérrez');
INSERT INTO Regiones VALUES(6, 'Uriangato');
INSERT INTO Regiones VALUES(6, 'Uruapan');
INSERT INTO Regiones VALUES(6, 'Veracruz');
INSERT INTO Regiones VALUES(6, 'Villaflores');
INSERT INTO Regiones VALUES(6, 'Villahermosa');
INSERT INTO Regiones VALUES(6, 'Xalapa');
INSERT INTO Regiones VALUES(6, 'Zacatecas');
INSERT INTO Regiones VALUES(6, 'Zamora');
INSERT INTO Regiones VALUES(6, 'Cinépolis Azcapotzalco');
INSERT INTO Regiones VALUES(6, 'Cinépolis City Center Zona Esmeralda');
INSERT INTO Regiones VALUES(6, 'Cinépolis Encuentro Fortuna');
INSERT INTO Regiones VALUES(6, 'Cinépolis Encuentro Tlalnepantla');
INSERT INTO Regiones VALUES(6, 'Cinépolis Galerías Atizapán');
INSERT INTO Regiones VALUES(6, 'Cinépolis Gustavo Baz');
INSERT INTO Regiones VALUES(6, 'Cinépolis Izcalli');
INSERT INTO Regiones VALUES(6, 'Cinépolis La Cúspide');
INSERT INTO Regiones VALUES(6, 'Cinépolis Multiplaza Arboledas');
INSERT INTO Regiones VALUES(6, 'Cinépolis Pabellón Río de los Remedios');
INSERT INTO Regiones VALUES(6, 'Cinépolis Pedregal Atizapán');
INSERT INTO Regiones VALUES(6, 'Cinépolis Pabellón Río de los Remedios');


